// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/weather/coords/{latitude}/{longitude}": {
            "get": {
                "description": "Fetches the current weather data for a specified latitude and longitude",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Fetches current weather by coordinates (latitude and longitude)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Latitude",
                        "name": "latitude",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Longitude",
                        "name": "longitude",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WeatherResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/weather/forecast/coords/{latitude}/{longitude}": {
            "get": {
                "description": "Fetches the weather forecast data for a specified latitude and longitude",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Fetches weather forecast by coordinates (latitude and longitude)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Latitude",
                        "name": "latitude",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Longitude",
                        "name": "longitude",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ForecastResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/weather/forecast/{city}": {
            "get": {
                "description": "Fetches the weather forecast data for a specified city",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Fetches weather forecast by city",
                "parameters": [
                    {
                        "type": "string",
                        "description": "City Name",
                        "name": "city",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ForecastResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/weather/{city}": {
            "get": {
                "description": "Fetches the current weather data for a specified city",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Fetches current weather by city",
                "parameters": [
                    {
                        "type": "string",
                        "description": "City Name",
                        "name": "city",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WeatherResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "types.City": {
            "type": "object",
            "properties": {
                "coord": {
                    "$ref": "#/definitions/types.Coord"
                },
                "country": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "population": {
                    "type": "integer"
                },
                "sunrise": {
                    "type": "integer"
                },
                "sunset": {
                    "type": "integer"
                },
                "timezone": {
                    "type": "integer"
                }
            }
        },
        "types.Clouds": {
            "type": "object",
            "properties": {
                "all": {
                    "type": "integer"
                }
            }
        },
        "types.Coord": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "types.ForecastItem": {
            "type": "object",
            "properties": {
                "clouds": {
                    "$ref": "#/definitions/types.Clouds"
                },
                "dt": {
                    "type": "integer"
                },
                "dt_txt": {
                    "type": "string"
                },
                "main": {
                    "$ref": "#/definitions/types.Main"
                },
                "pop": {
                    "type": "number"
                },
                "sys": {
                    "$ref": "#/definitions/types.Sys"
                },
                "visibility": {
                    "type": "integer"
                },
                "weather": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Weather"
                    }
                },
                "wind": {
                    "$ref": "#/definitions/types.Wind"
                }
            }
        },
        "types.ForecastResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "$ref": "#/definitions/types.City"
                },
                "cnt": {
                    "type": "integer"
                },
                "cod": {
                    "type": "string"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ForecastItem"
                    }
                },
                "message": {
                    "type": "integer"
                }
            }
        },
        "types.Main": {
            "type": "object",
            "properties": {
                "feels_like": {
                    "type": "number"
                },
                "grnd_level": {
                    "type": "integer"
                },
                "humidity": {
                    "type": "integer"
                },
                "pressure": {
                    "type": "integer"
                },
                "sea_level": {
                    "type": "integer"
                },
                "temp": {
                    "type": "number"
                },
                "temp_kf": {
                    "type": "number"
                },
                "temp_max": {
                    "type": "number"
                },
                "temp_min": {
                    "type": "number"
                }
            }
        },
        "types.Sys": {
            "type": "object",
            "properties": {
                "pod": {
                    "type": "string"
                }
            }
        },
        "types.Weather": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "main": {
                    "type": "string"
                }
            }
        },
        "types.WeatherResponse": {
            "type": "object",
            "properties": {
                "clouds": {
                    "type": "object",
                    "properties": {
                        "all": {
                            "type": "integer"
                        }
                    }
                },
                "cod": {
                    "type": "integer"
                },
                "coord": {
                    "type": "object",
                    "properties": {
                        "lat": {
                            "type": "number"
                        },
                        "lon": {
                            "type": "number"
                        }
                    }
                },
                "dt": {
                    "description": "Timestamp",
                    "type": "integer"
                },
                "main": {
                    "type": "object",
                    "properties": {
                        "feels_like": {
                            "type": "number"
                        },
                        "grnd_level": {
                            "type": "integer"
                        },
                        "humidity": {
                            "type": "integer"
                        },
                        "pressure": {
                            "type": "integer"
                        },
                        "sea_level": {
                            "type": "integer"
                        },
                        "temp": {
                            "type": "number"
                        },
                        "temp_max": {
                            "type": "number"
                        },
                        "temp_min": {
                            "type": "number"
                        }
                    }
                },
                "name": {
                    "type": "string"
                },
                "sys": {
                    "type": "object",
                    "properties": {
                        "country": {
                            "type": "string"
                        },
                        "sunrise": {
                            "type": "integer"
                        },
                        "sunset": {
                            "type": "integer"
                        }
                    }
                },
                "timezone": {
                    "type": "integer"
                },
                "visibility": {
                    "type": "integer"
                },
                "weather": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "description": {
                                "type": "string"
                            },
                            "icon": {
                                "type": "string"
                            },
                            "id": {
                                "type": "integer"
                            },
                            "main": {
                                "type": "string"
                            }
                        }
                    }
                },
                "wind": {
                    "type": "object",
                    "properties": {
                        "deg": {
                            "type": "integer"
                        },
                        "gust": {
                            "type": "number"
                        },
                        "speed": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "types.Wind": {
            "type": "object",
            "properties": {
                "deg": {
                    "type": "integer"
                },
                "gust": {
                    "type": "number"
                },
                "speed": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key authentication for accessing weather data",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Weather API",
	Description:      "API for fetching weather data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
